<a href="https://colab.research.google.com/github/aynaval/Hotel-booking-analysis_EDA/blob/main/EDA_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **KPIS for Hotel Industry**

---





1.   **RevPAR**

>Revenue per available room helps in evaluating the hotel’s operational performance. 

2.  **ALOS**

>The Average Length Of Stay 

>Calculated by dividing the occupied rooms by a number of bookings.

3. **Total Available Rooms**

>The number of rooms which are readily there to be booked in the hotel.

> Computed as sum of Available Rooms and also the number of Occupied Rooms.















In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.read_csv('/content/drive/MyDrive/Hotel booking analysis/Copy of Hotel Bookings.csv')

In [3]:
data.head(3)

hotel  is_canceled  ...  reservation_status  reservation_status_date
0  Resort Hotel            0  ...           Check-Out               2015-07-01
1  Resort Hotel            0  ...           Check-Out               2015-07-01
2  Resort Hotel            0  ...           Check-Out               2015-07-02

[3 rows x 32 columns]

In [4]:
data.tail(3)

hotel  is_canceled  ...  reservation_status  reservation_status_date
119387  City Hotel            0  ...           Check-Out               2017-09-07
119388  City Hotel            0  ...           Check-Out               2017-09-07
119389  City Hotel            0  ...           Check-Out               2017-09-07

[3 rows x 32 columns]

In [5]:
data.describe()

is_canceled  ...  total_of_special_requests
count  119390.000000  ...              119390.000000
mean        0.370416  ...                   0.571363
std         0.482918  ...                   0.792798
min         0.000000  ...                   0.000000
25%         0.000000  ...                   0.000000
50%         0.000000  ...                   0.000000
75%         1.000000  ...                   1.000000
max         1.000000  ...                   5.000000

[8 rows x 20 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [7]:
cols = pd.Series(data.columns)
cols

0                              hotel
1                        is_canceled
2                          lead_time
3                  arrival_date_year
4                 arrival_date_month
5           arrival_date_week_number
6          arrival_date_day_of_month
7            stays_in_weekend_nights
8               stays_in_week_nights
9                             adults
10                          children
11                            babies
12                              meal
13                           country
14                    market_segment
15              distribution_channel
16                 is_repeated_guest
17            previous_cancellations
18    previous_bookings_not_canceled
19                reserved_room_type
20                assigned_room_type
21                   booking_changes
22                      deposit_type
23                             agent
24                           company
25              days_in_waiting_list
26                     customer_type
2

# **Columns and their meaning**
0. hotel 
>Hotel (H1 = Resort Hotel or H2 = City Hotel)

1. is_canceled
>Value indicating if the booking was canceled (1) or not (0)

2. lead_time
>Number of days that elapsed between the entering date of the booking into the PMS and the arrival date

3. arrival_date_year
>Year of arrival date

4. arrival_date_month
>Month of arrival date

5. arrival_date_week_number
>Week number of year for arrival date

6. arrival_date_day_of_month
>Day of arrival date

7. stays_in_weekend_nights
>Number of weekend nights (Saturday or Sunday) the guest stayed or booked to stay at the hotel

8. stays_in_week_nights
>Number of week nights (Monday to Friday) the guest stayed or booked to stay at the hotel

9. adults
>Number of adults

10. children
>Number of children

11. babies
>Number of babies

12. meal
>Type of meal booked. Categories are presented in standard hospitality meal packages: Undefined/SC – no meal package; BB – Bed & Breakfast; HB – Half board (breakfast and one other meal – usually dinner); FB – Full board (breakfast, lunch and dinner)

13. country
>Country of origin. Categories are represented in the ISO 3155–3:2013 format

14. market_segment
>Market segment designation. In categories, the term “TA” means “Travel Agents” and “TO” means “Tour Operators”

15. distribution_channel
>Booking distribution channel. The term “TA” means “Travel Agents” and “TO” means “Tour Operators”

16. is_repeated_guest
>Value indicating if the booking name was from a repeated guest (1) or not (0)

17. previous_cancellations
>Number of previous bookings that were cancelled by the customer prior to the current booking

18. previous_bookings_not_canceled
>Number of previous bookings not cancelled by the customer prior to the current booking

19. reserved_room_type
>Code of room type reserved. Code is presented instead of designation for anonymity reasons.

20. assigned_room_type
>Code for the type of room assigned to the booking. Sometimes the assigned room type differs from the reserved room type due to hotel operation reasons (e.g. overbooking) or by customer request. Code is presented instead of designation for anonymity reasons.

21. booking_changes
>Number of changes/amendments made to the booking from the moment the booking was entered on the PMS until the moment of check-in or cancellation

22. deposit_type
>Indication on if the customer made a deposit to guarantee the booking. This variable can assume three categories: No Deposit – no deposit was made; Non Refund – a deposit was made in the value of the total stay cost; Refundable – a deposit was made with a value under the total cost of stay.

23. agent
>ID of the travel agency that made the booking

24. company
>ID of the company/entity that made the booking or responsible for paying the booking. ID is presented instead of designation for anonymity reasons

25. days_in_waiting_list
>Number of days the booking was in the waiting list before it was confirmed to the customer

26. customer_type
>Type of booking, assuming one of four categories: Contract - when the booking has an allotment or other type of contract associated to it; Group – when the booking is associated to a group; Transient – when the booking is not part of a group or contract, and is not associated to other transient booking; Transient-party – when the booking is transient, but is associated to at least other transient booking

27. adr
>Average Daily Rate as defined by dividing the sum of all lodging transactions by the total number of staying nights

28. required_car_parking_spaces
>Number of car parking spaces required by the customer

29. total_of_special_requests
>Number of special requests made by the customer (e.g. twin bed or high floor)

30. reservation_status
>Reservation last status, assuming one of three categories: Canceled – booking was canceled by the customer; Check-Out – customer has checked in but already departed; No-Show – customer did not check-in and did inform the hotel of the reason why

31. reservation_status_date
>Date at which the last status was set. This variable can be used in conjunction with the ReservationStatus to understand when was the

In [8]:
data.shape

(119390, 32)

In [9]:
data.size

3820480

In [10]:

for i in data.drop(['reservation_status_date','lead_time','arrival_date_week_number','arrival_date_day_of_month','stays_in_weekend_nights','stays_in_week_nights','previous_cancellations','previous_bookings_not_canceled','agent','company','days_in_waiting_list','adr'],axis = 1).columns:
  #print(i,data[i].unique() ,"\n")
  print(i, ": ")
  print(data[i].unique(),"\n\n")
  

hotel : 
['Resort Hotel' 'City Hotel'] 


is_canceled : 
[0 1] 


arrival_date_year : 
[2015 2016 2017] 


arrival_date_month : 
['July' 'August' 'September' 'October' 'November' 'December' 'January'
 'February' 'March' 'April' 'May' 'June'] 


adults : 
[ 2  1  3  4 40 26 50 27 55  0 20  6  5 10] 


children : 
[ 0.  1.  2. 10.  3. nan] 


babies : 
[ 0  1  2 10  9] 


meal : 
['BB' 'FB' 'HB' 'SC' 'Undefined'] 


country : 
['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' nan 'ROU' 'NOR' 'OMN' 'ARG' 'POL'
 'DEU' 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST'
 'CZE' 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR'
 'UKR' 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO'
 'ISR' 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM'
 'HRV' 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY'
 'KWT' 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN'
 'SYC' 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'L